services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: restaurante
    ports:
      - "3306:3306"
    volumes:
      - ./backend/database/restaurante.sql:/docker-entrypoint-initdb.d/database.sql
  back:
    build: ./backend
    ports:
      - "5001:5001"
    depends_on:
      - db
    environment:
      DB_HOST: db

  front:
    build: ./frontend
    ports:
      - "5000:5000"
    depends_on:
      - back